name: Docker

on:
  push:
    branches:
      - main

jobs:
  build_deploy_and_restart_docker_container:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_REPO }}
          tags: latest
    
      - name: Push XMRIG version to Docker Hub
        uses: docker/build-push-action@v1
        with:
          file: Dockerfile.xmrig
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_REPO }}
          tags: xmrig
