name: Docker

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build_deploy_and_restart_docker_container:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: ${{ secrets.DOCKERHUB_REPO }}
          tag_with_ref: true
